name: 'Detect Runner'
description: 'detect the github runner'

inputs:
  # token:
  #   description: "The GitHub Actions token."
  #   required: true
  #   # default: ${{ github.token }}
  gh-token:
    description: "The GitHub Actions token."
    required: true
    # default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'index.js'
