name: Build SLSA3 RW
on: 
  push:
  workflow_dispatch:

permissions: {}

jobs:
  # This Job builds our artifacts, uploads them to the workflow run, and
  # outputs their digest.
  build-and-attest:
    permissions:
      id-token: write
      attestations: write
      contents: read
    uses: ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml@dev
    with:
      build-runner-label: ubuntu-latest
      subject-path: app/build/libs/app.jar
