name: Check Repo Rules
on:
  # Only the default branch is supported.
  branch_protection_rule:
  schedule:
    # Weekly on Saturdays.
    - cron: '30 1 * * 6'
  push:
    branches: [ main, master ]
  pull_request:

# Declare default permissions as read only.
permissions: read-all

jobs:
  check-repo-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Checkout code"
        uses: ./.github/actions/check-repo-rules
        id: check-repo-rules
