name: SLSA Provenance with Gradle builder
on: [workflow_dispatch, push]

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_gradle_slsa3.yml@v1.9.0
    with:
      artifact-list: >-
        ./build/app/libs/app.jar,
        ./build/app/classes/java/main/my/example/gradle/project/App.class,
