name: SLSA Provenance with Gradle builder
on: [workflow_dispatch, pull_request]

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_gradle_slsa3.yml@v1.9.0
    with:
      artifact-list: ${{ github.workspace }}/app/build/libs/app.jar
      rekor-log-public: false
