name: Upload Download Test
on:
  pull_request:
jobs:
  upload-test:
    runs-on: ubuntu-latest
    steps:
      - id: write-file
        run: |
          echo "gundam" > ./my-file.txt
      - id: upload-artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: artifacts1
          path: ./my-file.txt
          if-no-files-found: error
          retention-days: 5
      - id: delete-file
        run: |
          rm ./my-file.txt
  download-test:
    needs: [upload-test]
    runs-on: ubuntu-latest
    steps:
      - id: download-artifact
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: artifacts1
      - id: read-file
        run: |
          cat ./my-file.txt
